FROM alpine

ARG LIBRESSL_VERSION=${LIBRESSL_VERSION}
ARG LIBRDKAFKA_VERSION=${LIBRDKAFKA_VERSION}

# Install librdkafka
RUN apk update && \
    apk add libressl${LIBRESSL_VERSION}-libcrypto libressl${LIBRESSL_VERSION}-libssl --update-cache --repository http://nl.alpinelinux.org/alpine/edge/main && \
    apk add librdkafka=${LIBRDKAFKA_VERSION} --update-cache --repository http://nl.alpinelinux.org/alpine/edge/community
