version: '3.4'
services:
  logic:
    build:
      context: ../../logic
      target: final
      args:
        GO_PROJECT_PATH: github.com/sysco-middleware/commander-boilerplate/logic
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: users
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
    networks:
      - postgres
      - kafka
  command:
    build:
      context: ../../command
      target: final
      args:
        GO_PROJECT_PATH: github.com/sysco-middleware/commander-boilerplate/command
    ports:
      - 5050:8080
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: command
      HOST_ADDRESS: :8080
      COMMANDER_EVENT_TOPIC: events
      COMMANDER_COMMAND_TOPIC: commands
    networks:
      - kafka
  projector:
    build:
      context: ../../projector
      target: final
      args:
        GO_PROJECT_PATH: github.com/sysco-middleware/commander-boilerplate/projector
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: projector
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
    networks:
      - kafka
      - postgres
  query:
    build:
      context: ../../query
      target: final
      args:
        GO_PROJECT_PATH: github.com/sysco-middleware/commander-boilerplate/query
    ports:
      - 5060:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
      HOST_ADDRESS: :8080
    networks:
      - postgres
networks:
  kafka:
    external:
      name: kafka
  postgres:
    external:
      name: postgres
